input:
  # Options:
  #   single_mesh
  #   labelled_components
  mode: single_mesh

  # Used when mode: single_mesh
  mesh_path: data/mesh_001/mesh_001.ply

  # Used when mode: labelled_components
  labelled_dir: data/sample_001
  dendrite_pattern: dendrite*.ply
  spine_pattern: spine*.ply

  # Mesh coordinate conversion to nm.
  # Use 1.0 if mesh is already in nm.
  # Use 1000000.0 if mesh is in mm and should be converted to nm.
  scale_to_nm: 1.0
  recenter: false


output:
  output_dir: outputs/mesh_001/mesh_001_splatting_membrane_psf
  output_name: mesh_001


grid:
  xy_um_per_px: 0.2
  z_step_um: 0.5

  # Options:
  #   false = render full mesh bounding box
  #   true  = render cropped centered ROI
  use_roi: true

  roi_size_um_x: 150.0
  roi_size_um_y: 150.0
  margin: 0.05


renderer:
  # Options:
  #   voxel_grid
  #   gaussian_splatting
  method: gaussian_splatting

  # Options:
  #   membrane
  #   pseudofilled
  labeling_mode: membrane

  # Used by voxel_grid and gaussian_splatting
  spacing_nm: 150
  batch_faces: 2048

  # Used only when labeling_mode: pseudofilled
  pseudofill_sigma_zyx: [2.0, 2.5, 2.5]

  # Final small density smoothing before PSF convolution in voxel_grid mode
  density_smooth_sigma_zyx: [0.6, 0.8, 0.8]
  density_normalize_sum: true


splatting:
  # Used when renderer.method: gaussian_splatting
  spacing_nm: 100

  # Gaussian splat width in voxel units: [Z, Y, X]
  sigma_zyx: [0.5, 0.8, 0.8]

  # Apply calibrated PSF after Gaussian splatting
  apply_psf: true

  # Surface point sampling seed
  seed: 0

  # Number of surface points processed per batch
  points_per_batch: 50000


psf:
  # Options:
  #   bornwolf_1p
  #   bornwolf_2p
  #   gaussian_2p
  mode: bornwolf_2p

  path: psfs/psf_bornwolf_488nm_NA1_xy200nm_z500nm_65x65x13.tif
  two_photon_like: true

  # Used only when mode: gaussian_2p
  shape_zyx: [13, 65, 65]
  lambda_nm: 488.0
  na: 1.0
  refractive_index: 1.33
  sigma_scale_xy: 1.0
  sigma_scale_z: 1.0


noise:
  enabled: false
  peak_photons: 500.0
  read_noise_std: 5.0
  seed: 0
  gaussian_chunk_slices: 16


masks:
  object_rel_threshold: 0.1
  spine_rel_threshold: 0.1
  dendrite_rel_threshold: 0.1

  # These are only useful for labelled_components mode.
  # For single_mesh mode, they are ignored.
  save_individual_spine_masks: false
  save_clean_component_images: false