"""
Create quick preview images for labelled-mesh rendering experiments.

This script must be run only after the rendering pipeline has completed
successfully using render.py.

Before running this script, make sure the renderer output directory contains:

    - a rendered image TIFF ending with:
          image.tif

    - a spine ground-truth mask ending with:
          spine_mask.tif

    - a dendrite ground-truth mask ending with:
          dendrite_mask.tif

These files are generated by render.py when running a labelled-mesh
experiment. This script does not perform rendering and does not generate
ground-truth masks.

The script creates:

    - maximum-intensity-projection PNG of the rendered image
    - maximum-intensity-projection PNG of the spine mask
    - maximum-intensity-projection PNG of the dendrite mask
    - full 3D RGB TIFF overlay containing:
          rendered image + spine mask + dendrite mask

The overlay TIFF is not a maximum-intensity projection. It preserves all
Z slices and can be opened as a stack in Fiji/ImageJ.

Mask colors in the overlay:

    - dendrite: cyan-blue
    - spine: orange

Run from the repository root:

    python scripts/make_overlay.py \
        --output-dir outputs/sample_001/gaussian_2p_voxelgrid_membrane

Generated files:

    previews/image_mip.png
    previews/spine_mask_mip.png
    previews/dendrite_mask_mip.png
    previews/overlay_stack.tif
"""

from pathlib import Path
import argparse

import matplotlib.pyplot as plt
import numpy as np
import tifffile


def normalize01(arr: np.ndarray) -> np.ndarray:
    """
    Normalize an array to the range [0, 1].

    If the array contains only zero or negative values, return an
    all-zero float32 array.
    """
    arr = arr.astype(np.float32)

    vmax = float(arr.max())

    if vmax <= 0:
        return np.zeros_like(arr, dtype=np.float32)

    return arr / vmax


def save_gray(path: Path, image: np.ndarray) -> None:
    """
    Save a 2D grayscale preview as a PNG file.
    """
    plt.figure(figsize=(8, 8))
    plt.imshow(image, cmap="gray")
    plt.axis("off")
    plt.tight_layout(pad=0)

    plt.savefig(
        path,
        dpi=200,
        bbox_inches="tight",
        pad_inches=0,
    )

    plt.close()


def save_overlay_stack(
    path: Path,
    image_stack: np.ndarray,
    spine_stack: np.ndarray,
    dendrite_stack: np.ndarray,
) -> None:
    """
    Save a full 3D RGB TIFF overlay.

    The input arrays are expected to have shape:

        Z, Y, X

    The saved RGB stack has shape:

        Z, Y, X, 3

    This function does not create a maximum-intensity projection.
    """
    if image_stack.shape != spine_stack.shape:
        raise ValueError(
            "Rendered image and spine mask have different shapes:\n"
            f"  image: {image_stack.shape}\n"
            f"  spine: {spine_stack.shape}"
        )

    if image_stack.shape != dendrite_stack.shape:
        raise ValueError(
            "Rendered image and dendrite mask have different shapes:\n"
            f"  image   : {image_stack.shape}\n"
            f"  dendrite: {dendrite_stack.shape}"
        )

    image = normalize01(image_stack)
    spine = spine_stack > 0
    dendrite = dendrite_stack > 0

    # Convert grayscale stack from (Z, Y, X) to RGB stack (Z, Y, X, 3).
    rgb = np.stack(
        [image, image, image],
        axis=-1,
    )

    # Color-blind-friendlier mask colors.
    dendrite_color = np.array(
        [0.0, 0.7, 1.0],
        dtype=np.float32,
    )

    spine_color = np.array(
        [1.0, 0.6, 0.0],
        dtype=np.float32,
    )

    alpha = 0.65

    # Add dendrite overlay.
    rgb[dendrite] = (
        (1.0 - alpha) * rgb[dendrite]
        + alpha * dendrite_color
    )

    # Add spine overlay.
    # If spine and dendrite masks overlap, the spine color is shown.
    rgb[spine] = (
        (1.0 - alpha) * rgb[spine]
        + alpha * spine_color
    )

    rgb_uint8 = (
        np.clip(rgb, 0.0, 1.0) * 255
    ).astype(np.uint8)

    tifffile.imwrite(
        path,
        rgb_uint8,
        photometric="rgb",
        compression="zlib",
        metadata={"axes": "ZYXS"},
    )


def find_one(output_dir: Path, pattern: str) -> Path:
    """
    Find one required renderer output file.

    If multiple files match, use the first file in sorted order.
    """
    matches = sorted(output_dir.glob(pattern))

    if len(matches) == 0:
        raise FileNotFoundError(
            f"Required renderer output not found: {pattern}\n"
            f"Checked directory: {output_dir}\n"
            "Run the labelled-mesh experiment with render.py before "
            "running make_overlay.py."
        )

    if len(matches) > 1:
        print(
            f"Warning: multiple files found for pattern '{pattern}'. "
            "Using:"
        )
        print(f"  {matches[0]}")

    return matches[0]


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Create MIP PNG previews and a full RGB TIFF overlay from "
            "labelled-mesh renderer outputs."
        )
    )

    parser.add_argument(
        "--output-dir",
        required=True,
        help="Renderer output directory from a labelled-mesh experiment",
    )

    args = parser.parse_args()

    output_dir = Path(args.output_dir)

    if not output_dir.exists():
        raise FileNotFoundError(
            f"Output directory does not exist:\n  {output_dir}\n"
            "Run render.py first or provide the correct renderer output folder."
        )

    if not output_dir.is_dir():
        raise NotADirectoryError(
            f"The supplied output path is not a directory:\n  {output_dir}"
        )

    image_path = find_one(
        output_dir,
        "*image.tif",
    )

    spine_path = find_one(
        output_dir,
        "*spine_mask.tif",
    )

    dendrite_path = find_one(
        output_dir,
        "*dendrite_mask.tif",
    )

    preview_dir = output_dir / "previews"
    preview_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("Loading renderer outputs:")
    print(f"  image   : {image_path}")
    print(f"  spine   : {spine_path}")
    print(f"  dendrite: {dendrite_path}")

    image = tifffile.imread(image_path)
    spine = tifffile.imread(spine_path)
    dendrite = tifffile.imread(dendrite_path)

    if image.ndim != 3:
        raise ValueError(
            "Expected rendered image to be a 3D TIFF stack with shape "
            f"(Z, Y, X), but received shape {image.shape}."
        )

    if spine.ndim != 3:
        raise ValueError(
            "Expected spine mask to be a 3D TIFF stack with shape "
            f"(Z, Y, X), but received shape {spine.shape}."
        )

    if dendrite.ndim != 3:
        raise ValueError(
            "Expected dendrite mask to be a 3D TIFF stack with shape "
            f"(Z, Y, X), but received shape {dendrite.shape}."
        )

    # Create MIPs only for the individual image and masks.
    image_mip = image.max(axis=0)
    spine_mip = spine.max(axis=0)
    dendrite_mip = dendrite.max(axis=0)

    image_mip_path = preview_dir / "image_mip.png"
    spine_mip_path = preview_dir / "spine_mask_mip.png"
    dendrite_mip_path = preview_dir / "dendrite_mask_mip.png"
    overlay_stack_path = preview_dir / "overlay_stack.tif"

    save_gray(
        image_mip_path,
        normalize01(image_mip),
    )

    save_gray(
        spine_mip_path,
        spine_mip > 0,
    )

    save_gray(
        dendrite_mip_path,
        dendrite_mip > 0,
    )

    # Save the full stack overlay without creating an overlay MIP.
    save_overlay_stack(
        overlay_stack_path,
        image,
        spine,
        dendrite,
    )

    print("Saved preview files:")
    print(f"  {image_mip_path}")
    print(f"  {spine_mip_path}")
    print(f"  {dendrite_mip_path}")
    print(f"  {overlay_stack_path}")


if __name__ == "__main__":
    main()